<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Area {
	static $swaggerTypes = array(
		'BackgroundColor' => 'Color',
		'FillFormat' => 'FillFormat',
		'ForegroundColor' => 'Color',
		'Formatting' => 'string',
		'InvertIfNegative' => 'bool',
		'Transparency' => 'float'

	);

	public $BackgroundColor; // Color
	public $FillFormat; // FillFormat
	public $ForegroundColor; // Color
	public $Formatting; // string
	public $InvertIfNegative; // bool
	public $Transparency; // float
	}

