<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AutoFitterOptions {
	static $swaggerTypes = array(
		'AutoFitMergedCells' => 'bool',
		'IgnoreHidden' => 'bool',
		'OnlyAuto' => 'bool'

	);

	public $AutoFitMergedCells; // bool
	public $IgnoreHidden; // bool
	public $OnlyAuto; // bool
	}

