<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AutoFilter {
	static $swaggerTypes = array(
		'FilterColumns' => 'array[FilterColumn]',
		'Range' => 'string',
		'Sorter' => 'DataSorter',
		'link' => 'Link'

	);

	public $FilterColumns; // array[FilterColumn]
	public $Range; // string
	public $Sorter; // DataSorter
	public $link; // Link
	}

