<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AutoShapesResponse {
	static $swaggerTypes = array(
		'AutoShapes' => 'AutoShapes',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $AutoShapes; // AutoShapes
	public $Code; // string
	public $Status; // string
	}

