<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Border {
	static $swaggerTypes = array(
		'LineStyle' => 'string',
		'Color' => 'Color',
		'BorderType' => 'string'

	);

	public $LineStyle; // string
	public $Color; // Color
	public $BorderType; // string
	}

