<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CellResponse {
	static $swaggerTypes = array(
		'Cell' => 'Cell',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Cell; // Cell
	public $Code; // string
	public $Status; // string
	}

