<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CellsDocumentPropertiesResponse {
	static $swaggerTypes = array(
		'DocumentProperties' => 'CellsDocumentProperties',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $DocumentProperties; // CellsDocumentProperties
	public $Code; // string
	public $Status; // string
	}

