<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CellsResponse {
	static $swaggerTypes = array(
		'Cells' => 'Cells',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Cells; // Cells
	public $Code; // string
	public $Status; // string
	}

