<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CellsDocumentProperties {
	static $swaggerTypes = array(
		'DocumentPropertyList' => 'array[CellsDocumentProperty]',
		'link' => 'Link'

	);

	public $DocumentPropertyList; // array[CellsDocumentProperty]
	public $link; // Link
	}

