<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CellsDocumentPropertyResponse {
	static $swaggerTypes = array(
		'DocumentProperty' => 'CellsDocumentProperty',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $DocumentProperty; // CellsDocumentProperty
	public $Code; // string
	public $Status; // string
	}

