<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Cell {
	static $swaggerTypes = array(
		'Name' => 'string',
		'Row' => 'int',
		'Column' => 'int',
		'Value' => 'string',
		'Type' => 'string',
		'Formula' => 'string',
		'IsFormula' => 'bool',
		'IsMerged' => 'bool',
		'IsArrayHeader' => 'bool',
		'IsInArray' => 'bool',
		'IsErrorValue' => 'bool',
		'IsInTable' => 'bool',
		'IsStyleSet' => 'bool',
		'HtmlString' => 'string',
		'Style' => 'LinkElement',
		'Worksheet' => 'string',
		'link' => 'Link'

	);

	public $Name; // string
	public $Row; // int
	public $Column; // int
	public $Value; // string
	public $Type; // string
	public $Formula; // string
	public $IsFormula; // bool
	public $IsMerged; // bool
	public $IsArrayHeader; // bool
	public $IsInArray; // bool
	public $IsErrorValue; // bool
	public $IsInTable; // bool
	public $IsStyleSet; // bool
	public $HtmlString; // string
	public $Style; // LinkElement
	public $Worksheet; // string
	public $link; // Link
	}

