<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CellsColor {
	static $swaggerTypes = array(
		'Color' => 'Color',
		'ColorIndex' => 'int',
		'IsShapeColor' => 'bool',
		'ThemeColor' => 'ThemeColor',
		'Type' => 'string'

	);

	public $Color; // Color
	public $ColorIndex; // int
	public $IsShapeColor; // bool
	public $ThemeColor; // ThemeColor
	public $Type; // string
	}

