<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Cells {
	static $swaggerTypes = array(
		'MaxRow' => 'int',
		'MaxColumn' => 'int',
		'CellCount' => 'int',
		'Rows' => 'LinkElement',
		'Columns' => 'LinkElement',
		'CellList' => 'array[LinkElement]',
		'link' => 'Link'

	);

	public $MaxRow; // int
	public $MaxColumn; // int
	public $CellCount; // int
	public $Rows; // LinkElement
	public $Columns; // LinkElement
	public $CellList; // array[LinkElement]
	public $link; // Link
	}

