<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ChartAreaResponse {
	static $swaggerTypes = array(
		'ChartArea' => 'ChartArea',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $ChartArea; // ChartArea
	public $Code; // string
	public $Status; // string
	}

