<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ChartsResponse {
	static $swaggerTypes = array(
		'Charts' => 'Charts',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Charts; // Charts
	public $Code; // string
	public $Status; // string
	}

