<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ChartArea {
	static $swaggerTypes = array(
		'Area' => 'Area',
		'AutoScaleFont' => 'bool',
		'BackgroundMode' => 'string',
		'Border' => 'Line',
		'Font' => 'Font',
		'IsAutomaticSize' => 'bool',
		'IsInnerMode' => 'bool',
		'Shadow' => 'bool',
		'ShapeProperties' => 'array[LinkElement]',
		'Width' => 'int',
		'Height' => 'int',
		'X' => 'int',
		'Y' => 'int',
		'link' => 'Link'

	);

	public $Area; // Area
	public $AutoScaleFont; // bool
	public $BackgroundMode; // string
	public $Border; // Line
	public $Font; // Font
	public $IsAutomaticSize; // bool
	public $IsInnerMode; // bool
	public $Shadow; // bool
	public $ShapeProperties; // array[LinkElement]
	public $Width; // int
	public $Height; // int
	public $X; // int
	public $Y; // int
	public $link; // Link
	}

