<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ColorFilter {
	static $swaggerTypes = array(
		'FilterByFillColor' => 'string'

	);

	public $FilterByFillColor; // string
	}

