<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Column {
	static $swaggerTypes = array(
		'GroupLevel' => 'int',
		'Index' => 'int',
		'IsHidden' => 'bool',
		'Width' => 'float',
		'Style' => 'LinkElement',
		'link' => 'Link'

	);

	public $GroupLevel; // int
	public $Index; // int
	public $IsHidden; // bool
	public $Width; // float
	public $Style; // LinkElement
	public $link; // Link
	}

