<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ColumnResponse {
	static $swaggerTypes = array(
		'Column' => 'Column',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Column; // Column
	public $Code; // string
	public $Status; // string
	}

