<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ColumnsResponse {
	static $swaggerTypes = array(
		'Columns' => 'Columns',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Columns; // Columns
	public $Code; // string
	public $Status; // string
	}

