<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Columns {
	static $swaggerTypes = array(
		'MaxColumn' => 'int',
		'ColumnsCount' => 'int',
		'ColumnsList' => 'array[LinkElement]',
		'link' => 'Link'

	);

	public $MaxColumn; // int
	public $ColumnsCount; // int
	public $ColumnsList; // array[LinkElement]
	public $link; // Link
	}

