<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CommentResponse {
	static $swaggerTypes = array(
		'Comment' => 'Comment',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Comment; // Comment
	public $Code; // string
	public $Status; // string
	}

