<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Comment {
	static $swaggerTypes = array(
		'CellName' => 'string',
		'Author' => 'string',
		'HtmlNote' => 'string',
		'Note' => 'string',
		'AutoSize' => 'bool',
		'IsVisible' => 'bool',
		'Width' => 'int',
		'Height' => 'int',
		'TextHorizontalAlignment' => 'string',
		'TextOrientationType' => 'string',
		'TextVerticalAlignment' => 'string',
		'link' => 'Link'

	);

	public $CellName; // string
	public $Author; // string
	public $HtmlNote; // string
	public $Note; // string
	public $AutoSize; // bool
	public $IsVisible; // bool
	public $Width; // int
	public $Height; // int
	public $TextHorizontalAlignment; // string
	public $TextOrientationType; // string
	public $TextVerticalAlignment; // string
	public $link; // Link
	}

