<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CommentsResponse {
	static $swaggerTypes = array(
		'Comments' => 'Comments',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Comments; // Comments
	public $Code; // string
	public $Status; // string
	}

