<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CreatePivotTableRequest {
	static $swaggerTypes = array(
		'Name' => 'string',
		'SourceData' => 'string',
		'DestCellName' => 'string',
		'UseSameSource' => 'bool',
		'PivotFieldRows' => 'array[int]',
		'PivotFieldColumns' => 'array[int]',
		'PivotFieldData' => 'array[int]'

	);

	public $Name; // string
	public $SourceData; // string
	public $DestCellName; // string
	public $UseSameSource; // bool
	public $PivotFieldRows; // array[int]
	public $PivotFieldColumns; // array[int]
	public $PivotFieldData; // array[int]
	}

