<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CustomFilter {
	static $swaggerTypes = array(
		'Criteria' => 'object',
		'FilterOperatorType' => 'string'

	);

	public $Criteria; // object
	public $FilterOperatorType; // string
	}

