<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DataSorter {
	static $swaggerTypes = array(
		'CaseSensitive' => 'string',
		'HasHeaders' => 'string',
		'KeyList' => 'array[SortKey]',
		'SortLeftToRight' => 'string'

	);

	public $CaseSensitive; // string
	public $HasHeaders; // string
	public $KeyList; // array[SortKey]
	public $SortLeftToRight; // string
	}

