<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DateTimeGroupItem {
	static $swaggerTypes = array(
		'DateTimeGroupingType' => 'string',
		'Day' => 'int',
		'Hour' => 'int',
		'Minute' => 'int',
		'Month' => 'int',
		'Second' => 'int',
		'Year' => 'int'

	);

	public $DateTimeGroupingType; // string
	public $Day; // int
	public $Hour; // int
	public $Minute; // int
	public $Month; // int
	public $Second; // int
	public $Year; // int
	}

