<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DynamicFilter {
	static $swaggerTypes = array(
		'DynamicFilterType' => 'string',
		'MaxValue' => 'object',
		'Value' => 'object'

	);

	public $DynamicFilterType; // string
	public $MaxValue; // object
	public $Value; // object
	}

