<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FillFormat {
	static $swaggerTypes = array(
		'Type' => 'string',
		'SolidFill' => 'SolidFill',
		'PatternFill' => 'PatternFill',
		'TextureFill' => 'TextureFill',
		'GradientFill' => 'GradientFill',
		'ImageData' => 'string'

	);

	public $Type; // string
	public $SolidFill; // SolidFill
	public $PatternFill; // PatternFill
	public $TextureFill; // TextureFill
	public $GradientFill; // GradientFill
	public $ImageData; // string
	}

