<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FillFormatResponse {
	static $swaggerTypes = array(
		'FillFormat' => 'FillFormat',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $FillFormat; // FillFormat
	public $Code; // string
	public $Status; // string
	}

