<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FilterColumn {
	static $swaggerTypes = array(
		'FieldIndex' => 'int',
		'FilterType' => 'string',
		'MultipleFilters' => 'MultipleFilters',
		'ColorFilter' => 'ColorFilter',
		'CustomFilters' => 'array[CustomFilter]',
		'DynamicFilter' => 'DynamicFilter',
		'IconFilter' => 'IconFilter',
		'Top10Filter' => 'Top10Filter',
		'Visibledropdown' => 'string'

	);

	public $FieldIndex; // int
	public $FilterType; // string
	public $MultipleFilters; // MultipleFilters
	public $ColorFilter; // ColorFilter
	public $CustomFilters; // array[CustomFilter]
	public $DynamicFilter; // DynamicFilter
	public $IconFilter; // IconFilter
	public $Top10Filter; // Top10Filter
	public $Visibledropdown; // string
	}

