<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Font {
	static $swaggerTypes = array(
		'Color' => 'Color',
		'DoubleSize' => 'float',
		'IsBold' => 'bool',
		'IsItalic' => 'bool',
		'IsStrikeout' => 'bool',
		'IsSubscript' => 'bool',
		'IsSuperscript' => 'bool',
		'Name' => 'string',
		'Size' => 'int',
		'Underline' => 'string'

	);

	public $Color; // Color
	public $DoubleSize; // float
	public $IsBold; // bool
	public $IsItalic; // bool
	public $IsStrikeout; // bool
	public $IsSubscript; // bool
	public $IsSuperscript; // bool
	public $Name; // string
	public $Size; // int
	public $Underline; // string
	}

