<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class GradientFill {
	static $swaggerTypes = array(
		'FillType' => 'string',
		'DirectionType' => 'string',
		'Angle' => 'float',
		'GradientStops' => 'array[GradientFillStop]'

	);

	public $FillType; // string
	public $DirectionType; // string
	public $Angle; // float
	public $GradientStops; // array[GradientFillStop]
	}

