<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class GradientFillStop {
	static $swaggerTypes = array(
		'Color' => 'Color',
		'Position' => 'float',
		'Transparency' => 'float'

	);

	public $Color; // Color
	public $Position; // float
	public $Transparency; // float
	}

