<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Hyperlink {
	static $swaggerTypes = array(
		'Address' => 'string',
		'Area' => 'CellArea',
		'ScreenTip' => 'string',
		'TextToDisplay' => 'string',
		'link' => 'Link'

	);

	public $Address; // string
	public $Area; // CellArea
	public $ScreenTip; // string
	public $TextToDisplay; // string
	public $link; // Link
	}

