<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class IconFilter {
	static $swaggerTypes = array(
		'IconId' => 'int',
		'IconSetType' => 'string'

	);

	public $IconId; // int
	public $IconSetType; // string
	}

