<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ImportOption {
	static $swaggerTypes = array(
		'DestinationWorksheet' => 'string',
		'IsInsert' => 'bool'

	);

	public $DestinationWorksheet; // string
	public $IsInsert; // bool
	}

