<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class LegendResponse {
	static $swaggerTypes = array(
		'Legend' => 'Legend',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Legend; // Legend
	public $Code; // string
	public $Status; // string
	}

