<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Line {
	static $swaggerTypes = array(
		'BeginArrowLength' => 'string',
		'BeginArrowWidth' => 'string',
		'BeginType' => 'string',
		'CapType' => 'string',
		'Color' => 'Color',
		'CompoundType' => 'string',
		'DashType' => 'string',
		'EndArrowLength' => 'string',
		'EndArrowWidth' => 'string',
		'EndType' => 'string',
		'GradientFill' => 'GradientFill',
		'IsAuto' => 'bool',
		'IsAutomaticColor' => 'bool',
		'IsVisible' => 'bool',
		'JoinType' => 'string',
		'Style' => 'string',
		'Transparency' => 'float',
		'Weight' => 'string',
		'WeightPt' => 'float'

	);

	public $BeginArrowLength; // string
	public $BeginArrowWidth; // string
	public $BeginType; // string
	public $CapType; // string
	public $Color; // Color
	public $CompoundType; // string
	public $DashType; // string
	public $EndArrowLength; // string
	public $EndArrowWidth; // string
	public $EndType; // string
	public $GradientFill; // GradientFill
	public $IsAuto; // bool
	public $IsAutomaticColor; // bool
	public $IsVisible; // bool
	public $JoinType; // string
	public $Style; // string
	public $Transparency; // float
	public $Weight; // string
	public $WeightPt; // float
	}

