<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class LineResponse {
	static $swaggerTypes = array(
		'Line' => 'Line',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Line; // Line
	public $Code; // string
	public $Status; // string
	}

