<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MergedCell {
	static $swaggerTypes = array(
		'EndColumn' => 'int',
		'EndRow' => 'int',
		'StartColumn' => 'int',
		'StartRow' => 'int',
		'link' => 'Link'

	);

	public $EndColumn; // int
	public $EndRow; // int
	public $StartColumn; // int
	public $StartRow; // int
	public $link; // Link
	}

