<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MergedCellsResponse {
	static $swaggerTypes = array(
		'MergedCells' => 'MergedCells',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $MergedCells; // MergedCells
	public $Code; // string
	public $Status; // string
	}

