<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MergedCellResponse {
	static $swaggerTypes = array(
		'MergedCell' => 'MergedCell',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $MergedCell; // MergedCell
	public $Code; // string
	public $Status; // string
	}

