<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MultipleFilters {
	static $swaggerTypes = array(
		'MatchBlank' => 'string',
		'MultipleFilterList' => 'array[DateTimeGroupItem]'

	);

	public $MatchBlank; // string
	public $MultipleFilterList; // array[DateTimeGroupItem]
	}

