<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Name {
	static $swaggerTypes = array(
		'Comment' => 'string',
		'WorksheetIndex' => 'int',
		'IsReferred' => 'bool',
		'IsVisible' => 'bool',
		'R1C1RefersTo' => 'string',
		'RefersTo' => 'string',
		'Text' => 'string',
		'link' => 'Link'

	);

	public $Comment; // string
	public $WorksheetIndex; // int
	public $IsReferred; // bool
	public $IsVisible; // bool
	public $R1C1RefersTo; // string
	public $RefersTo; // string
	public $Text; // string
	public $link; // Link
	}

