<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class NameResponse {
	static $swaggerTypes = array(
		'Name' => 'Name',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Name; // Name
	public $Code; // string
	public $Status; // string
	}

