<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class NamesResponse {
	static $swaggerTypes = array(
		'Names' => 'Names',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Names; // Names
	public $Code; // string
	public $Status; // string
	}

