<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OleObjectResponse {
	static $swaggerTypes = array(
		'OleObject' => 'OleObject',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $OleObject; // OleObject
	public $Code; // string
	public $Status; // string
	}

