<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class OleObjectsResponse {
	static $swaggerTypes = array(
		'OleObjects' => 'OleObjects',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $OleObjects; // OleObjects
	public $Code; // string
	public $Status; // string
	}

