<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PatternFill {
	static $swaggerTypes = array(
		'Pattern' => 'string',
		'BackgroundCellsColor' => 'CellsColor',
		'ForegroundCellsColor' => 'CellsColor',
		'ForegroundColor' => 'Color',
		'BackgroundColor' => 'Color',
		'BackTransparency' => 'float',
		'ForeTransparency' => 'float'

	);

	public $Pattern; // string
	public $BackgroundCellsColor; // CellsColor
	public $ForegroundCellsColor; // CellsColor
	public $ForegroundColor; // Color
	public $BackgroundColor; // Color
	public $BackTransparency; // float
	public $ForeTransparency; // float
	}

