<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PicFormatOption {
	static $swaggerTypes = array(
		'Type' => 'string',
		'Scale' => 'float',
		'Left' => 'float',
		'Right' => 'float',
		'Top' => 'float',
		'Bottom' => 'float'

	);

	public $Type; // string
	public $Scale; // float
	public $Left; // float
	public $Right; // float
	public $Top; // float
	public $Bottom; // float
	}

