<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Pictures {
	static $swaggerTypes = array(
		'PictureList' => 'array[LinkElement]',
		'link' => 'Link'

	);

	public $PictureList; // array[LinkElement]
	public $link; // Link
	}

