<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PictureResponse {
	static $swaggerTypes = array(
		'Picture' => 'Picture',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Picture; // Picture
	public $Code; // string
	public $Status; // string
	}

