<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Picture {
	static $swaggerTypes = array(
		'BorderLineColor' => 'Color',
		'BorderWeight' => 'float',
		'OriginalHeight' => 'int',
		'OriginalWidth' => 'int',
		'ImageFormat' => 'string',
		'SourceFullName' => 'string',
		'Name' => 'string',
		'MsoDrawingType' => 'string',
		'AutoShapeType' => 'string',
		'Placement' => 'string',
		'UpperLeftRow' => 'int',
		'Top' => 'int',
		'UpperLeftColumn' => 'int',
		'Left' => 'int',
		'LowerRightRow' => 'int',
		'Bottom' => 'int',
		'LowerRightColumn' => 'int',
		'Right' => 'int',
		'Width' => 'int',
		'Height' => 'int',
		'X' => 'int',
		'Y' => 'int',
		'RotationAngle' => 'float',
		'HtmlText' => 'string',
		'Text' => 'string',
		'AlternativeText' => 'string',
		'TextHorizontalAlignment' => 'string',
		'TextHorizontalOverflow' => 'string',
		'TextOrientationType' => 'string',
		'TextVerticalAlignment' => 'string',
		'TextVerticalOverflow' => 'string',
		'IsGroup' => 'bool',
		'IsHidden' => 'bool',
		'IsLockAspectRatio' => 'bool',
		'IsLocked' => 'bool',
		'IsPrintable' => 'bool',
		'IsTextWrapped' => 'bool',
		'IsWordArt' => 'bool',
		'LinkedCell' => 'string',
		'ZOrderPosition' => 'int',
		'link' => 'Link'

	);

	public $BorderLineColor; // Color
	public $BorderWeight; // float
	public $OriginalHeight; // int
	public $OriginalWidth; // int
	public $ImageFormat; // string
	public $SourceFullName; // string
	public $Name; // string
	public $MsoDrawingType; // string
	public $AutoShapeType; // string
	public $Placement; // string
	public $UpperLeftRow; // int
	public $Top; // int
	public $UpperLeftColumn; // int
	public $Left; // int
	public $LowerRightRow; // int
	public $Bottom; // int
	public $LowerRightColumn; // int
	public $Right; // int
	public $Width; // int
	public $Height; // int
	public $X; // int
	public $Y; // int
	public $RotationAngle; // float
	public $HtmlText; // string
	public $Text; // string
	public $AlternativeText; // string
	public $TextHorizontalAlignment; // string
	public $TextHorizontalOverflow; // string
	public $TextOrientationType; // string
	public $TextVerticalAlignment; // string
	public $TextVerticalOverflow; // string
	public $IsGroup; // bool
	public $IsHidden; // bool
	public $IsLockAspectRatio; // bool
	public $IsLocked; // bool
	public $IsPrintable; // bool
	public $IsTextWrapped; // bool
	public $IsWordArt; // bool
	public $LinkedCell; // string
	public $ZOrderPosition; // int
	public $link; // Link
	}

