<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PicturesResponse {
	static $swaggerTypes = array(
		'Pictures' => 'Pictures',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Pictures; // Pictures
	public $Code; // string
	public $Status; // string
	}

