<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotTableResponse {
	static $swaggerTypes = array(
		'PivotTable' => 'PivotTable',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $PivotTable; // PivotTable
	public $Code; // string
	public $Status; // string
	}

