<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotFilter {
	static $swaggerTypes = array(
		'AutoFilter' => 'AutoFilter',
		'EvaluationOrder' => 'int',
		'FieldIndex' => 'int',
		'FilterType' => 'string',
		'MeasureFldIndex' => 'int',
		'MemberPropertyFieldIndex' => 'int',
		'Name' => 'string',
		'Value1' => 'string',
		'Value2' => 'string'

	);

	public $AutoFilter; // AutoFilter
	public $EvaluationOrder; // int
	public $FieldIndex; // int
	public $FilterType; // string
	public $MeasureFldIndex; // int
	public $MemberPropertyFieldIndex; // int
	public $Name; // string
	public $Value1; // string
	public $Value2; // string
	}

