<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotTablesResponse {
	static $swaggerTypes = array(
		'PivotTables' => 'PivotTables',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $PivotTables; // PivotTables
	public $Code; // string
	public $Status; // string
	}

