<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotItem {
	static $swaggerTypes = array(
		'Index' => 'int',
		'IsHidden' => 'bool',
		'Name' => 'string',
		'Value' => 'object'

	);

	public $Index; // int
	public $IsHidden; // bool
	public $Name; // string
	public $Value; // object
	}

