<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotTableFieldRequest {
	static $swaggerTypes = array(
		'Data' => 'array[int]'

	);

	public $Data; // array[int]
	}

