<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotTable {
	static $swaggerTypes = array(
		'AltTextDescription' => 'string',
		'AltTextTitle' => 'string',
		'AutoFormatType' => 'string',
		'BaseFields' => 'array[PivotField]',
		'ColumnFields' => 'array[PivotField]',
		'ColumnGrand' => 'bool',
		'ColumnHeaderCaption' => 'string',
		'ColumnRange' => 'CellArea',
		'CustomListSort' => 'bool',
		'DataBodyRange' => 'CellArea',
		'DataField' => 'PivotField',
		'DataFields' => 'array[PivotField]',
		'DataSource' => 'array[string]',
		'DisplayErrorString' => 'bool',
		'DisplayImmediateItems' => 'bool',
		'DisplayNullString' => 'bool',
		'EnableDataValueEditing' => 'bool',
		'EnableDrilldown' => 'bool',
		'EnableFieldDialog' => 'bool',
		'EnableFieldList' => 'bool',
		'EnableWizard' => 'bool',
		'ErrorString' => 'string',
		'FieldListSortAscending' => 'bool',
		'GrandTotalName' => 'string',
		'HasBlankRows' => 'bool',
		'Indent' => 'int',
		'IsAutoFormat' => 'bool',
		'IsGridDropZones' => 'bool',
		'IsMultipleFieldFilters' => 'bool',
		'IsSelected' => 'bool',
		'ItemPrintTitles' => 'bool',
		'ManualUpdate' => 'bool',
		'MergeLabels' => 'bool',
		'MissingItemsLimit' => 'string',
		'Name' => 'string',
		'NullString' => 'string',
		'PageFieldOrder' => 'string',
		'PageFields' => 'array[PivotField]',
		'PageFieldWrapCount' => 'int',
		'PivotFilters' => 'array[PivotFilter]',
		'PivotTableStyleName' => 'string',
		'PivotTableStyleType' => 'string',
		'PreserveFormatting' => 'bool',
		'PrintDrill' => 'bool',
		'PrintTitles' => 'bool',
		'RefreshDataFlag' => 'bool',
		'RefreshDataOnOpeningFile' => 'bool',
		'RowFields' => 'array[PivotField]',
		'RowGrand' => 'bool',
		'RowHeaderCaption' => 'string',
		'RowRange' => 'CellArea',
		'SaveData' => 'bool',
		'ShowDataTips' => 'bool',
		'ShowDrill' => 'bool',
		'ShowEmptyCol' => 'bool',
		'ShowEmptyRow' => 'bool',
		'ShowMemberPropertyTips' => 'bool',
		'ShowPivotStyleColumnHeader' => 'bool',
		'ShowPivotStyleColumnStripes' => 'bool',
		'ShowPivotStyleLastColumn' => 'bool',
		'ShowPivotStyleRowHeader' => 'bool',
		'ShowPivotStyleRowStripes' => 'bool',
		'ShowRowHeaderCaption' => 'bool',
		'ShowValuesRow' => 'bool',
		'SubtotalHiddenPageItems' => 'bool',
		'TableRange1' => 'CellArea',
		'TableRange2' => 'CellArea',
		'Tag' => 'string',
		'link' => 'Link'

	);

	public $AltTextDescription; // string
	public $AltTextTitle; // string
	public $AutoFormatType; // string
	public $BaseFields; // array[PivotField]
	public $ColumnFields; // array[PivotField]
	public $ColumnGrand; // bool
	public $ColumnHeaderCaption; // string
	public $ColumnRange; // CellArea
	public $CustomListSort; // bool
	public $DataBodyRange; // CellArea
	public $DataField; // PivotField
	public $DataFields; // array[PivotField]
	public $DataSource; // array[string]
	public $DisplayErrorString; // bool
	public $DisplayImmediateItems; // bool
	public $DisplayNullString; // bool
	public $EnableDataValueEditing; // bool
	public $EnableDrilldown; // bool
	public $EnableFieldDialog; // bool
	public $EnableFieldList; // bool
	public $EnableWizard; // bool
	public $ErrorString; // string
	public $FieldListSortAscending; // bool
	public $GrandTotalName; // string
	public $HasBlankRows; // bool
	public $Indent; // int
	public $IsAutoFormat; // bool
	public $IsGridDropZones; // bool
	public $IsMultipleFieldFilters; // bool
	public $IsSelected; // bool
	public $ItemPrintTitles; // bool
	public $ManualUpdate; // bool
	public $MergeLabels; // bool
	public $MissingItemsLimit; // string
	public $Name; // string
	public $NullString; // string
	public $PageFieldOrder; // string
	public $PageFields; // array[PivotField]
	public $PageFieldWrapCount; // int
	public $PivotFilters; // array[PivotFilter]
	public $PivotTableStyleName; // string
	public $PivotTableStyleType; // string
	public $PreserveFormatting; // bool
	public $PrintDrill; // bool
	public $PrintTitles; // bool
	public $RefreshDataFlag; // bool
	public $RefreshDataOnOpeningFile; // bool
	public $RowFields; // array[PivotField]
	public $RowGrand; // bool
	public $RowHeaderCaption; // string
	public $RowRange; // CellArea
	public $SaveData; // bool
	public $ShowDataTips; // bool
	public $ShowDrill; // bool
	public $ShowEmptyCol; // bool
	public $ShowEmptyRow; // bool
	public $ShowMemberPropertyTips; // bool
	public $ShowPivotStyleColumnHeader; // bool
	public $ShowPivotStyleColumnStripes; // bool
	public $ShowPivotStyleLastColumn; // bool
	public $ShowPivotStyleRowHeader; // bool
	public $ShowPivotStyleRowStripes; // bool
	public $ShowRowHeaderCaption; // bool
	public $ShowValuesRow; // bool
	public $SubtotalHiddenPageItems; // bool
	public $TableRange1; // CellArea
	public $TableRange2; // CellArea
	public $Tag; // string
	public $link; // Link
	}

