<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PivotField {
	static $swaggerTypes = array(
		'AutoShowCount' => 'int',
		'AutoShowField' => 'int',
		'AutoSortField' => 'int',
		'BaseField' => 'int',
		'BaseIndex' => 'int',
		'BaseItem' => 'int',
		'BaseItemPosition' => 'string',
		'CurrentPageItem' => 'integer',
		'DataDisplayFormat' => 'string',
		'DisplayName' => 'string',
		'DragToColumn' => 'bool',
		'DragToData' => 'bool',
		'DragToHide' => 'bool',
		'DragToPage' => 'bool',
		'DragToRow' => 'bool',
		'Function' => 'string',
		'InsertBlankRow' => 'bool',
		'IsAscendShow' => 'bool',
		'IsAscendSort' => 'bool',
		'IsAutoShow' => 'bool',
		'IsAutoSort' => 'bool',
		'IsAutoSubtotals' => 'bool',
		'IsCalculatedField' => 'bool',
		'IsIncludeNewItemsInFilter' => 'bool',
		'IsInsertPageBreaksBetweenItems' => 'bool',
		'IsMultipleItemSelectionAllowed' => 'bool',
		'IsRepeatItemLabels' => 'bool',
		'ItemCount' => 'int',
		'Items' => 'array[string]',
		'Name' => 'string',
		'Number' => 'int',
		'NumberFormat' => 'string',
		'OriginalItems' => 'array[string]',
		'PivotItems' => 'array[PivotItem]',
		'Position' => 'int',
		'ShowAllItems' => 'bool',
		'ShowCompact' => 'bool',
		'ShowInOutlineForm' => 'bool',
		'ShowSubtotalAtTop' => 'bool'

	);

	public $AutoShowCount; // int
	public $AutoShowField; // int
	public $AutoSortField; // int
	public $BaseField; // int
	public $BaseIndex; // int
	public $BaseItem; // int
	public $BaseItemPosition; // string
	public $CurrentPageItem; // integer
	public $DataDisplayFormat; // string
	public $DisplayName; // string
	public $DragToColumn; // bool
	public $DragToData; // bool
	public $DragToHide; // bool
	public $DragToPage; // bool
	public $DragToRow; // bool
	public $Function; // string
	public $InsertBlankRow; // bool
	public $IsAscendShow; // bool
	public $IsAscendSort; // bool
	public $IsAutoShow; // bool
	public $IsAutoSort; // bool
	public $IsAutoSubtotals; // bool
	public $IsCalculatedField; // bool
	public $IsIncludeNewItemsInFilter; // bool
	public $IsInsertPageBreaksBetweenItems; // bool
	public $IsMultipleItemSelectionAllowed; // bool
	public $IsRepeatItemLabels; // bool
	public $ItemCount; // int
	public $Items; // array[string]
	public $Name; // string
	public $Number; // int
	public $NumberFormat; // string
	public $OriginalItems; // array[string]
	public $PivotItems; // array[PivotItem]
	public $Position; // int
	public $ShowAllItems; // bool
	public $ShowCompact; // bool
	public $ShowInOutlineForm; // bool
	public $ShowSubtotalAtTop; // bool
	}

