<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ProtectSheetParameter {
	static $swaggerTypes = array(
		'ProtectionType' => 'string',
		'Password' => 'string',
		'AllowEditArea' => 'array[string]',
		'AllowDeletingColumn' => 'string',
		'AllowDeletingRow' => 'string',
		'AllowFiltering' => 'string',
		'AllowFormattingCell' => 'string',
		'AllowFormattingColumn' => 'string',
		'AllowFormattingRow' => 'string',
		'AllowInsertingColumn' => 'string',
		'AllowInsertingHyperlink' => 'string',
		'AllowInsertingRow' => 'string',
		'AllowSelectingLockedCell' => 'string',
		'AllowSelectingUnlockedCell' => 'string',
		'AllowSorting' => 'string',
		'AllowUsingPivotTable' => 'string'

	);

	public $ProtectionType; // string
	public $Password; // string
	public $AllowEditArea; // array[string]
	public $AllowDeletingColumn; // string
	public $AllowDeletingRow; // string
	public $AllowFiltering; // string
	public $AllowFormattingCell; // string
	public $AllowFormattingColumn; // string
	public $AllowFormattingRow; // string
	public $AllowInsertingColumn; // string
	public $AllowInsertingHyperlink; // string
	public $AllowInsertingRow; // string
	public $AllowSelectingLockedCell; // string
	public $AllowSelectingUnlockedCell; // string
	public $AllowSorting; // string
	public $AllowUsingPivotTable; // string
	}

