<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class RowResponse {
	static $swaggerTypes = array(
		'Row' => 'Row',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Row; // Row
	public $Code; // string
	public $Status; // string
	}

