<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Rows {
	static $swaggerTypes = array(
		'MaxRow' => 'int',
		'RowsCount' => 'int',
		'RowsList' => 'array[LinkElement]',
		'link' => 'Link'

	);

	public $MaxRow; // int
	public $RowsCount; // int
	public $RowsList; // array[LinkElement]
	public $link; // Link
	}

