<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class RowsResponse {
	static $swaggerTypes = array(
		'Rows' => 'Rows',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Rows; // Rows
	public $Code; // string
	public $Status; // string
	}

