<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SaveOptions {
	static $swaggerTypes = array(
		'CachedFileFolder' => 'string',
		'ClearData' => 'bool',
		'CreateDirectory' => 'bool',
		'EnableHTTPCompression' => 'bool',
		'RefreshChartCache' => 'bool',
		'SortNames' => 'bool',
		'ValidateMergedAreas' => 'bool'

	);

	public $CachedFileFolder; // string
	public $ClearData; // bool
	public $CreateDirectory; // bool
	public $EnableHTTPCompression; // bool
	public $RefreshChartCache; // bool
	public $SortNames; // bool
	public $ValidateMergedAreas; // bool
	}

