<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SingleValue {
	static $swaggerTypes = array(
		'ValueType' => 'ValueType',
		'Value' => 'string'

	);

	public $ValueType; // ValueType
	public $Value; // string
	}

