<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SolidFill {
	static $swaggerTypes = array(
		'Color' => 'Color',
		'CellsColor' => 'CellsColor',
		'Transparency' => 'float'

	);

	public $Color; // Color
	public $CellsColor; // CellsColor
	public $Transparency; // float
	}

