<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SortKey {
	static $swaggerTypes = array(
		'Key' => 'int',
		'SortOrder' => 'string'

	);

	public $Key; // int
	public $SortOrder; // string
	}

