<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SplitResultDocument {
	static $swaggerTypes = array(
		'Id' => 'int',
		'link' => 'Link'

	);

	public $Id; // int
	public $link; // Link
	}

