<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Style {
	static $swaggerTypes = array(
		'Font' => 'Font',
		'Name' => 'string',
		'CultureCustom' => 'string',
		'Custom' => 'string',
		'BackgroundColor' => 'Color',
		'ForegroundColor' => 'Color',
		'IsFormulaHidden' => 'bool',
		'IsDateTime' => 'bool',
		'IsTextWrapped' => 'bool',
		'IsGradient' => 'bool',
		'IsLocked' => 'bool',
		'IsPercent' => 'bool',
		'ShrinkToFit' => 'bool',
		'IndentLevel' => 'int',
		'Number' => 'int',
		'RotationAngle' => 'int',
		'Pattern' => 'string',
		'TextDirection' => 'string',
		'VerticalAlignment' => 'string',
		'HorizontalAlignment' => 'string',
		'BorderCollection' => 'array[Border]',
		'link' => 'Link'

	);

	public $Font; // Font
	public $Name; // string
	public $CultureCustom; // string
	public $Custom; // string
	public $BackgroundColor; // Color
	public $ForegroundColor; // Color
	public $IsFormulaHidden; // bool
	public $IsDateTime; // bool
	public $IsTextWrapped; // bool
	public $IsGradient; // bool
	public $IsLocked; // bool
	public $IsPercent; // bool
	public $ShrinkToFit; // bool
	public $IndentLevel; // int
	public $Number; // int
	public $RotationAngle; // int
	public $Pattern; // string
	public $TextDirection; // string
	public $VerticalAlignment; // string
	public $HorizontalAlignment; // string
	public $BorderCollection; // array[Border]
	public $link; // Link
	}

