<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class StyleResponse {
	static $swaggerTypes = array(
		'Style' => 'Style',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Style; // Style
	public $Code; // string
	public $Status; // string
	}

