<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextItems {
	static $swaggerTypes = array(
		'TextItemList' => 'array[TextItem]',
		'link' => 'Link'

	);

	public $TextItemList; // array[TextItem]
	public $link; // Link
	}

