<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TextureFill {
	static $swaggerTypes = array(
		'Type' => 'string',
		'Transparency' => 'float',
		'Scale' => 'float',
		'TilePicOption' => 'TilePicOption',
		'PicFormatOption' => 'PicFormatOption',
		'Image' => 'LinkElement'

	);

	public $Type; // string
	public $Transparency; // float
	public $Scale; // float
	public $TilePicOption; // TilePicOption
	public $PicFormatOption; // PicFormatOption
	public $Image; // LinkElement
	}

