<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ThemeColor {
	static $swaggerTypes = array(
		'ColorType' => 'string',
		'Tint' => 'float'

	);

	public $ColorType; // string
	public $Tint; // float
	}

