<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TilePicOption {
	static $swaggerTypes = array(
		'OffsetX' => 'float',
		'OffsetY' => 'float',
		'ScaleX' => 'float',
		'ScaleY' => 'float',
		'AlignmentType' => 'string',
		'MirrorType' => 'string'

	);

	public $OffsetX; // float
	public $OffsetY; // float
	public $ScaleX; // float
	public $ScaleY; // float
	public $AlignmentType; // string
	public $MirrorType; // string
	}

