<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TitleResponse {
	static $swaggerTypes = array(
		'Title' => 'Title',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Title; // Title
	public $Code; // string
	public $Status; // string
	}

