<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Top10Filter {
	static $swaggerTypes = array(
		'Criteria' => 'string',
		'IsPercent' => 'string',
		'IsTop' => 'string',
		'Items' => 'int'

	);

	public $Criteria; // string
	public $IsPercent; // string
	public $IsTop; // string
	public $Items; // int
	}

