<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ValidationResponse {
	static $swaggerTypes = array(
		'Validation' => 'Validation',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Validation; // Validation
	public $Code; // string
	public $Status; // string
	}

