<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Validations {
	static $swaggerTypes = array(
		'Count' => 'int',
		'ValidationList' => 'array[LinkElement]',
		'link' => 'Link'

	);

	public $Count; // int
	public $ValidationList; // array[LinkElement]
	public $link; // Link
	}

