<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Validation {
	static $swaggerTypes = array(
		'AlertStyle' => 'string',
		'AreaList' => 'array[CellArea]',
		'ErrorMessage' => 'string',
		'ErrorTitle' => 'string',
		'Formula1' => 'string',
		'Formula2' => 'string',
		'IgnoreBlank' => 'bool',
		'InCellDropDown' => 'bool',
		'InputMessage' => 'string',
		'InputTitle' => 'string',
		'Operator' => 'string',
		'ShowError' => 'bool',
		'ShowInput' => 'bool',
		'Type' => 'string',
		'Value1' => 'string',
		'Value2' => 'string',
		'link' => 'Link'

	);

	public $AlertStyle; // string
	public $AreaList; // array[CellArea]
	public $ErrorMessage; // string
	public $ErrorTitle; // string
	public $Formula1; // string
	public $Formula2; // string
	public $IgnoreBlank; // bool
	public $InCellDropDown; // bool
	public $InputMessage; // string
	public $InputTitle; // string
	public $Operator; // string
	public $ShowError; // bool
	public $ShowInput; // bool
	public $Type; // string
	public $Value1; // string
	public $Value2; // string
	public $link; // Link
	}

