<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ValidationsResponse {
	static $swaggerTypes = array(
		'Validations' => 'Validations',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Validations; // Validations
	public $Code; // string
	public $Status; // string
	}

