<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Worksheets {
	static $swaggerTypes = array(
		'WorksheetList' => 'array[LinkElement]',
		'link' => 'Link'

	);

	public $WorksheetList; // array[LinkElement]
	public $link; // Link
	}

