<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorksheetMovingRequest {
	static $swaggerTypes = array(
		'DestinationWorksheet' => 'string',
		'Position' => 'string'

	);

	public $DestinationWorksheet; // string
	public $Position; // string
	}

