<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorksheetsResponse {
	static $swaggerTypes = array(
		'Worksheets' => 'Worksheets',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Worksheets; // Worksheets
	public $Code; // string
	public $Status; // string
	}

