<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorksheetReplaceResponse {
	static $swaggerTypes = array(
		'Matches' => 'int',
		'Worksheet' => 'LinkElement',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Matches; // int
	public $Worksheet; // LinkElement
	public $Code; // string
	public $Status; // string
	}

