<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorkbookResponse {
	static $swaggerTypes = array(
		'Workbook' => 'Workbook',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Workbook; // Workbook
	public $Code; // string
	public $Status; // string
	}

