<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Worksheet {
	static $swaggerTypes = array(
		'Links' => 'array[Link]',
		'DisplayRightToLeft' => 'bool',
		'DisplayZeros' => 'bool',
		'FirstVisibleColumn' => 'int',
		'FirstVisibleRow' => 'int',
		'Name' => 'string',
		'Index' => 'int',
		'IsGridlinesVisible' => 'bool',
		'IsOutlineShown' => 'bool',
		'IsPageBreakPreview' => 'bool',
		'IsVisible' => 'bool',
		'IsProtected' => 'bool',
		'IsRowColumnHeadersVisible' => 'bool',
		'IsRulerVisible' => 'bool',
		'IsSelected' => 'bool',
		'TabColor' => 'Color',
		'TransitionEntry' => 'bool',
		'TransitionEvaluation' => 'bool',
		'Type' => 'string',
		'ViewType' => 'string',
		'VisibilityType' => 'string',
		'Zoom' => 'int',
		'Cells' => 'LinkElement',
		'Charts' => 'LinkElement',
		'AutoShapes' => 'LinkElement',
		'OleObjects' => 'LinkElement',
		'Comments' => 'LinkElement',
		'Pictures' => 'LinkElement',
		'MergedCells' => 'LinkElement',
		'Validations' => 'LinkElement',
		'ConditionalFormattings' => 'LinkElement',
		'Hyperlinks' => 'LinkElement'

	);

	public $Links; // array[Link]
	public $DisplayRightToLeft; // bool
	public $DisplayZeros; // bool
	public $FirstVisibleColumn; // int
	public $FirstVisibleRow; // int
	public $Name; // string
	public $Index; // int
	public $IsGridlinesVisible; // bool
	public $IsOutlineShown; // bool
	public $IsPageBreakPreview; // bool
	public $IsVisible; // bool
	public $IsProtected; // bool
	public $IsRowColumnHeadersVisible; // bool
	public $IsRulerVisible; // bool
	public $IsSelected; // bool
	public $TabColor; // Color
	public $TransitionEntry; // bool
	public $TransitionEvaluation; // bool
	public $Type; // string
	public $ViewType; // string
	public $VisibilityType; // string
	public $Zoom; // int
	public $Cells; // LinkElement
	public $Charts; // LinkElement
	public $AutoShapes; // LinkElement
	public $OleObjects; // LinkElement
	public $Comments; // LinkElement
	public $Pictures; // LinkElement
	public $MergedCells; // LinkElement
	public $Validations; // LinkElement
	public $ConditionalFormattings; // LinkElement
	public $Hyperlinks; // LinkElement
	}

