<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorkbookProtectionRequest {
	static $swaggerTypes = array(
		'ProtectionType' => 'string',
		'Password' => 'string'

	);

	public $ProtectionType; // string
	public $Password; // string
	}

