<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorkbookEncryptionRequest {
	static $swaggerTypes = array(
		'EncryptionType' => 'string',
		'KeyLength' => 'int',
		'Password' => 'string'

	);

	public $EncryptionType; // string
	public $KeyLength; // int
	public $Password; // string
	}

