<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WorksheetResponse {
	static $swaggerTypes = array(
		'Worksheet' => 'Worksheet',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Worksheet; // Worksheet
	public $Code; // string
	public $Status; // string
	}

