<?php
namespace Aspose\Cells\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Workbook {
	static $swaggerTypes = array(
		'FileName' => 'string',
		'Links' => 'array[Link]',
		'Worksheets' => 'LinkElement',
		'DefaultStyle' => 'LinkElement',
		'DocumentProperties' => 'LinkElement',
		'Names' => 'LinkElement',
		'IsWriteProtected' => 'string',
		'IsProtected' => 'string',
		'IsEncryption' => 'string',
		'Password' => 'string'

	);

	public $FileName; // string
	public $Links; // array[Link]
	public $Worksheets; // LinkElement
	public $DefaultStyle; // LinkElement
	public $DocumentProperties; // LinkElement
	public $Names; // LinkElement
	public $IsWriteProtected; // string
	public $IsProtected; // string
	public $IsEncryption; // string
	public $Password; // string
	}

